<div style="margin-top: 20px; margin-bottom: 20px; padding-top: 38px; padding-bottom: 38px;border-top: 1px dotted #ccc; border-bottom: 1px dotted #ccc; text-align: center;">
    <a href="https://mvp.microsoft.com/zh-tw/PublicProfile/5003734">
        <div>
            <img src="mvp-logo.png" alt="微軟最有價值專家 2020-2021" />
        </div>
        <div>
            <strong>微軟最有價值專家 2020-2021</strong>
        </div>
    </a>
</div>
